// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css"; // já contém @font-face
import styles from "./(privada)/privateLayout.module.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
      </head>
      <body className="antialiased">
        <div className={styles.imgbackground}></div>
        <div className={styles.imgbackgroundMedia}></div>
        <Toaster richColors position="top-right" />
        {children}
      </body>
    </html>
  );
}
